services:
  stats-server:
    build: ./stats/stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db

  stats-db:
    image: postgres:16.1
    container_name: postgres_stats_db
    environment:
      - POSTGRES_PASSWORD=stats
      - POSTGRES_USER=stats
      - POSTGRES_DB=stats
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    build: ./main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
#      - stats-server

  ewm-db:
    image: postgres:16.1
    container_name: postgres_ewn_db
    environment:
      - POSTGRES_PASSWORD=main
      - POSTGRES_USER=main
      - POSTGRES_DB=main
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10